<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        /** 
            Set the margins of the page to 0, so the footer and the header
            can be of the full height and width !
         **/
        @page {
            margin: 0cm 0cm;
        }

        /** Define now the real margins of every page in the PDF **/
        body {
            margin-top: 3cm;
            margin-left: 1cm;
            margin-right: 1cm;
            margin-bottom: 1cm;
            font-family: 'Courier'
        }

        /** Define the header rules **/
        header {
            position: fixed;
            top: 0cm;
            left: 1cm;
            right: 1cm;
            height: 3cm;

            /** Extra personal styles **/
            background-color: white
            text-align: center;
            line-height: 1cm;
        }

        /** Define the footer rules **/
        footer {
            position: fixed; 
            bottom: 0cm; 
            left: 1cm; 
            right: 1cm;
            height: 1cm;

            /** Extra personal styles **/
            background-color: white;
            text-align: center;
            line-height: 1cm;
        }

#balanta {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#balanta td, #balanta th {
  border: 1px solid #ddd;
  padding: 2px;
}

#balanta tr:nth-child(even){background-color: #f2f2f2;}

#balanta th {
  padding-top: 2px;
  padding-bottom: 2px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
    </style>
</head>
<body>
    <!-- Define header and footer blocks before your content -->
    <header>
        <table>
            <tbody>
                <tr>
                    <td>
                       <div style="min-width:10cm;font-family: Helvetica;font-size:14px;font-weight:bold;">
                            <?=$t('balanta_pdf_societate');?>: <span style="font-size:14px;"><?=$balantaInNav->Name;?></span>
                            <br/>
                            <?=$t('balanta_pdf_cod_unic');?>: <?=$cif;?>
                            </div>
                    </td>
                    <td style="text-align:center;font-family: Helvetica;font-size:14px;font-weight:bold;">
                        <div style="min-width:11cm;">
                            <?=$t('balanta_pdf_titlu');?><br>
                            <?=$t('balanta_pdf_perioada');?>: 01.01.<?=(1*date("Y")-1);?> - <?=date('d.m.Y');?> 
                        </div>
                    </td>
                    <td>
                        <div style="min-width:3cm;font-family: Helvetica;font-size:14px;font-weight:bold;">
                            
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </header>

<footer>
    Copyright &copy; <?php echo date("Y");?> 
</footer>

<!-- Wrap the content of your PDF inside a main tag -->
<main>
    <p style="page-break-after: never;">
    <table id="balanta">
      <tr>
        <th><?=$t('balanta_pdf_data_document');?></th>
        <th><?=$t('balanta_pdf_data_scadenta');?></th>
        <th><?=$t('balanta_pdf_tip_document');?></th>
        <th><?=$t('balanta_pdf_numar');?></th>
        <th><?=$t('balanta_pdf_grupa_inregistrare');?></th>
        <th><?=$t('balanta_pdf_suma_debit');?></th>
        <th><?=$t('balanta_pdf_suma_credit');?></th>
        <th><?=$t('balanta_pdf_sold_debit');?></th>
        <th><?=$t('balanta_pdf_sold_credit');?></th>
     </tr>
       <?php
       $rowCount=0;
        foreach($balantaInNav->CustLedgerEntry as $row){
            $rowCount++;
       ?>     
        <tr>
            <td><?=$row->DocumentDate;?></td>
            <td><?=(gettype($row->DueDate)=='string'?$row->DueDate:'');?></td>
            <td><?=$row->DocumentType;?></td>
            <td><?=$row->DocumentNo;?></td>
            <td><?=$row->CustomerPostingGroup;?></td>
            <td><?=$row->DebitAmount;?></td>
            <td><?=$row->CreditAmount;?></td>
            <td><?=$row->DebitBalance;?></td>
            <td><?=$row->CreditBalance;?></td>
         </tr>
       <?php 
       }
       ?>      
    </p>
</main>
</body>
</html>
