ALTER TABLE portal_color.nom_products
  ALTER COLUMN pid_category DROP DEFAULT;

drop view portal_color.v_nom_products;
drop view portal_color.v_favorites;
drop view portal_color.v_cerere_products;
drop view portal_color.v_basket;
drop view portal_color.v_offer_products_from_cmsales;

-- portal_color.v_nom_products source

CREATE OR REPLACE VIEW portal_color.v_nom_products
AS SELECT np.appid,
    np.pid,
    np.product_code,
    np.product_name_ro,
    np.pid_category,
    np.size_length,
    np.size_width,
    np.size_thickness,
    np.size_diameter,
    np.size_height,
    np.size_alloy,
    np.size_type,
    np.size_roll_weight,
    np.um1,
    np.um2,
    np.um1_to_um2,
    np.product_name_en,
    np.um_base,
    np.is_active,
    np.additional_info,
    np.cu_debitare,
    np.aliaj,
    json_agg(json_build_object('pid_parent_category', ncp.parent_pid, 'pid_category', ncp.pid, 'category_name_ro', ncp.name_ro, 'category_name_en', ncp.name_en, 'with_length', ncp.with_length, 'with_width', ncp.with_width, 'with_thickness', ncp.with_thickness, 'with_diameter', ncp.with_diameter, 'with_height', ncp.with_height, 'with_alloy', ncp.with_alloy, 'with_type', ncp.with_type, 'with_roll_weight', ncp.with_roll_weight, 'lantHierarchyCategories', '')) AS categories
   FROM portal_color.nom_products np
     LEFT JOIN portal_color.nom_category_product ncp ON ncp.pid = ANY (np.pid_category)
  GROUP BY np.pid, np.appid, np.product_code, np.product_name_ro, np.pid_category, np.size_length, np.size_width, np.size_thickness, np.size_diameter, np.size_height, np.size_alloy, np.size_type, np.size_roll_weight, np.um1, np.um2, np.um1_to_um2, np.product_name_en, np.um_base, np.is_active, np.additional_info, np.cu_debitare, np.aliaj;
 
-- portal_color.v_favorites source

CREATE OR REPLACE VIEW portal_color.v_favorites
AS SELECT f.appid,
    f.userid,
    np.pid_category,
    f.product_code,
    f.pid_product,
    np.product_name_ro,
    np.product_name_en,
    f.q_nr_buc,
    np.um1,
    np.um2,
    f.qum1,
    f.qum2,
    np.um1_to_um2,
    f.size_length,
    f.size_width,
    f.size_thickness,
    f.size_diameter,
    f.size_height,
    f.size_alloy,
    f.size_type,
    f.track_date,
    np.um_base,
    np.is_active,
    u.cif,
    u.company_code,
    json_agg(json_build_object('pid_parent_category', ncp.parent_pid, 'pid_category', ncp.pid, 'category_name_ro', ncp.name_ro, 'category_name_en', ncp.name_en, 'with_length', ncp.with_length, 'with_width', ncp.with_width, 'with_thickness', ncp.with_thickness, 'with_diameter', ncp.with_diameter, 'with_height', ncp.with_height, 'with_alloy', ncp.with_alloy, 'with_type', ncp.with_type, 'with_roll_weight', ncp.with_roll_weight)) AS categories
   FROM portal_color.favorites f
     LEFT JOIN portal_color.nom_products np ON f.product_code::text = np.product_code::text
     LEFT JOIN portal_color.nom_category_product ncp ON ncp.pid = ANY (np.pid_category)
     LEFT JOIN portal_color.users u ON f.userid::text = u.userid::text
  GROUP BY f.appid, f.userid, np.pid_category, f.product_code, f.pid_product, np.product_name_ro, np.product_name_en, f.q_nr_buc, np.um1, np.um2, f.qum1, f.qum2, np.um1_to_um2, f.size_length, f.size_width, f.size_thickness, f.size_diameter, f.size_height, f.size_alloy, f.size_type, f.track_date, np.um_base, np.is_active, u.cif, u.company_code;

  -- portal_color.v_cerere_products source

 CREATE OR REPLACE VIEW portal_color.v_cerere_products
AS SELECT opfu.appid,
    opfu.id_offer,
    opfu.product_code,
    opfu.q_nr_buc,
    opfu.size_length,
    opfu.size_width,
    opfu.size_thickness,
    opfu.size_diameter,
    opfu.size_height,
    opfu.size_alloy,
    opfu.size_type,
    opfu.qum1,
    opfu.um1,
    opfu.qum2,
    opfu.um2,
    opfu.cu_debitare,
    opfu.size_length_cutting,
    opfu.size_width_cutting,
    opfu.observatii,
    np.pid AS pid_product,
    np.pid_category,
    np.product_name_ro,
    np.product_name_en,
    np.um_base,
    np.is_active,
    opfu.nr_ord,
    opfu.tip_um,
    json_agg(json_build_object('pid_parent_category', ncp.parent_pid, 
			'pid_category', ncp.pid,
	        'category_name_ro', ncp.name_ro, 
	        'category_name_en',  ncp.name_en, 
	        'with_length', ncp.with_length, 
	        'with_width', ncp.with_width, 
	        'with_thickness', ncp.with_thickness, 
	        'with_diameter', ncp.with_diameter, 
	        'with_height', ncp.with_height, 
	        'with_alloy', ncp.with_alloy, 
	        'with_type', ncp.with_type, 
	        'with_roll_weight', ncp.with_roll_weight)
        ) AS categories
   FROM portal_color.offer_products_from_user opfu
   left join portal_color.nom_products np on opfu.product_code::text = np.product_code::text
   left JOIN portal_color.nom_category_product ncp ON ncp.pid = ANY (np.pid_category)
   group by 
   opfu.appid,
    opfu.id_offer,
    opfu.product_code,
    opfu.q_nr_buc,
    opfu.size_length,
    opfu.size_width,
    opfu.size_thickness,
    opfu.size_diameter,
    opfu.size_height,
    opfu.size_alloy,
    opfu.size_type,
    opfu.qum1,
    opfu.um1,
    opfu.qum2,
    opfu.um2,
    opfu.cu_debitare,
    opfu.size_length_cutting,
    opfu.size_width_cutting,
    opfu.observatii,
    np.pid,
    np.pid_category,
    np.product_name_ro,
    np.product_name_en,
    np.um_base,
    np.is_active,
    opfu.nr_ord,
    opfu.tip_um;

  -- portal_color.v_basket source

 CREATE OR REPLACE VIEW portal_color.v_basket
AS SELECT b.appid,
    b.userid,
    np.pid_category,
    b.product_code,
    b.pid_product,
    np.product_name_ro,
    np.product_name_en,
    b.q_nr_buc,
    np.um1,
    np.um2,
    b.qum1,
    b.qum2,
    np.um1_to_um2,
    b.size_length,
    b.size_width,
    b.size_thickness,
    b.size_diameter,
    b.size_height,
    b.size_alloy,
    b.size_type,
    b.cu_debitare,
    b.size_length_cutting,
    b.size_width_cutting,
    b.track_date,
    np.um_base,
    np.is_active,
    u.cif,
    u.company_code,
    b.free_comments,
    b.nr_ord,
    b.tip_um,
    json_agg(json_build_object('pid_parent_category', ncp.parent_pid, 
			'pid_category', ncp.pid,
	        'category_name_ro', ncp.name_ro, 
	        'category_name_en',  ncp.name_en, 
	        'with_length', ncp.with_length, 
	        'with_width', ncp.with_width, 
	        'with_thickness', ncp.with_thickness, 
	        'with_diameter', ncp.with_diameter, 
	        'with_height', ncp.with_height, 
	        'with_alloy', ncp.with_alloy, 
	        'with_type', ncp.with_type, 
	        'with_roll_weight', ncp.with_roll_weight)
        ) AS categories
   FROM portal_color.basket b
   left join portal_color.nom_products np on b.product_code::text = np.product_code::text
   left JOIN portal_color.nom_category_product ncp ON ncp.pid = ANY (np.pid_category)
   left join portal_color.users u on b.userid::text = u.userid::text
   group by 
   b.appid,
    b.userid,
    np.pid_category,
    b.product_code,
    b.pid_product,
    np.product_name_ro,
    np.product_name_en,
    b.q_nr_buc,
    np.um1,
    np.um2,
    b.qum1,
    b.qum2,
    np.um1_to_um2,
    b.size_length,
    b.size_width,
    b.size_thickness,
    b.size_diameter,
    b.size_height,
    b.size_alloy,
    b.size_type,
    b.cu_debitare,
    b.size_length_cutting,
    b.size_width_cutting,
    b.track_date,
    np.um_base,
    np.is_active,
    u.cif,
    u.company_code,
    b.free_comments,
    b.nr_ord,
    b.tip_um;
  -- portal_color.v_offer_products_from_cmsales source

CREATE OR REPLACE VIEW portal_color.v_offer_products_from_cmsales
AS SELECT opfc.appid,
    opfc.id_offer,
    opfc.offer_slid,
    opfc.product_code,
    np.pid AS pid_product,
    np.pid_category,
    np.product_name_ro,
    np.product_name_en,
    np.size_length,
    np.size_width,
    np.size_thickness,
    np.size_diameter,
    np.size_height,
    np.size_alloy,
    np.size_type,
    opfc.status,
    1::numeric * opfc.q1 AS q1,
    opfc.um1,
    1::numeric * opfc.q2 AS q2,
    opfc.um2,
    opfc.um1_to_um2,
    opfc.tip_um,
    opfc.nr_buc,
    opfc.q_kg,
    opfc.tva_proc,
    opfc.cu_cheltuieli_transport,
    opfc.curseur,
    opfc.id_depozit,
    opfc.termen_livrare,
    opfc.cu_debitare,
    opfc.size_length AS size_length_from_sales,
    opfc.size_width AS size_width_from_sales,
    opfc.pret_mediu_calculat_um1_ron,
    opfc.pret_mediu_calculat_um1_eur,
    opfc.pret_mediu_calculat_um2_ron,
    opfc.pret_mediu_calculat_um2_eur,
    opfc.pret_mediu_calculat_um1_huf,
    opfc.pret_mediu_calculat_um2_huf,
    opfc.val_finala_fara_tva_ron,
    opfc.val_tva_ron,
    opfc.val_finala_cu_tva_ron,
    opfc.val_finala_fara_tva_eur,
    opfc.val_tva_eur,
    opfc.val_finala_cu_tva_eur,
    opfc.val_finala_fara_tva_huf,
    opfc.val_tva_huf,
    opfc.val_finala_cu_tva_huf,
    opfc.cost_livrare_ron,
    opfc.cost_livrare_eur,
    opfc.cost_livrare_huf,
    opfc.observatii,
    opfc.discount_proc,
    opfc.nr_ord,
    opfc.val_baza_ron,
    opfc.val_baza_eur,
    opfc.val_baza_huf,
    json_agg(json_build_object('pid_parent_category', ncp.parent_pid, 
			'pid_category', ncp.pid,
	        'category_name_ro', ncp.name_ro, 
	        'category_name_en',  ncp.name_en, 
	        'with_length', ncp.with_length, 
	        'with_width', ncp.with_width, 
	        'with_thickness', ncp.with_thickness, 
	        'with_diameter', ncp.with_diameter, 
	        'with_height', ncp.with_height, 
	        'with_alloy', ncp.with_alloy, 
	        'with_type', ncp.with_type, 
	        'with_roll_weight', ncp.with_roll_weight)
        ) AS categories
   FROM portal_color.offer_products_from_cmsales opfc
   left join portal_color.nom_products np on opfc.product_code::text = np.product_code::text
   left JOIN portal_color.nom_category_product ncp ON ncp.pid = ANY (np.pid_category)
   group by 
   opfc.appid,
    opfc.id_offer,
    opfc.offer_slid,
    opfc.product_code,
    np.pid,
    np.pid_category,
    np.product_name_ro,
    np.product_name_en,
    np.size_length,
    np.size_width,
    np.size_thickness,
    np.size_diameter,
    np.size_height,
    np.size_alloy,
    np.size_type,
    opfc.status,
    opfc.q1,
    opfc.um1,
    opfc.q2,
    opfc.um2,
    opfc.um1_to_um2,
    opfc.tip_um,
    opfc.nr_buc,
    opfc.q_kg,
    opfc.tva_proc,
    opfc.cu_cheltuieli_transport,
    opfc.curseur,
    opfc.id_depozit,
    opfc.termen_livrare,
    opfc.cu_debitare,
    opfc.size_length,
    opfc.size_width,
    opfc.pret_mediu_calculat_um1_ron,
    opfc.pret_mediu_calculat_um1_eur,
    opfc.pret_mediu_calculat_um2_ron,
    opfc.pret_mediu_calculat_um2_eur,
    opfc.pret_mediu_calculat_um1_huf,
    opfc.pret_mediu_calculat_um2_huf,
    opfc.val_finala_fara_tva_ron,
    opfc.val_tva_ron,
    opfc.val_finala_cu_tva_ron,
    opfc.val_finala_fara_tva_eur,
    opfc.val_tva_eur,
    opfc.val_finala_cu_tva_eur,
    opfc.val_finala_fara_tva_huf,
    opfc.val_tva_huf,
    opfc.val_finala_cu_tva_huf,
    opfc.cost_livrare_ron,
    opfc.cost_livrare_eur,
    opfc.cost_livrare_huf,
    opfc.observatii,
    opfc.discount_proc,
    opfc.nr_ord,
    opfc.val_baza_ron,
    opfc.val_baza_eur,
    opfc.val_baza_huf;

-- portal_color.newview source

CREATE OR REPLACE VIEW portal_color.v_offers_from_user
AS select 
	ofu.*,
	concat(u.first_name, ' ', u.last_name) as nume_utilizator 
from portal_color.offer_from_user ofu 
left join portal_color.users u on u.userid = ofu.track_user_id;
