export type TArticleOfferedFromSales = {
    appid: string;
    offerId:string;
    offerSlid:string;
    productPid:string;
    productCode:string;
    categoryPid: string;
    categoryName: string;
    productName: string;
    productNameRO: string;
    productNameEN: string;
    productNameBG: string;
    status:string;
    q1 : number;
    um1 : string;
    q2 : number | null;
    um2 : string | null;
    um1_to_um2 : number | null;
    tip_um : string;
    nrBuc : number | null;
    qKg  : number | null;
    tvaProc : number | null;
    cuCheltuieliTransport: string|null;
    curseur : number | null;
    l:number|null;
    w:number|null;
    t:number|null;
    d:number|null;
    h:number|null;
    a:string|null;
    k:string|null;
    g:number|null;
    idDepozit : number | null;
    termenLivrare : string;
    pretMediuCalculatUM1RON : number | null;
    pretMediuCalculatUM1EUR : number | null;
    pretMediuCalculatUM2RON : number | null;
    pretMediuCalculatUM2EUR : number | null;
    pretMediuCalculatUM1HUF : number | null;
    pretMediuCalculatUM2HUF : number | null;
    valFinalaFaraTvaRON : number | null;
    valTvaRON : number | null;
    valFinalaCuTvaRON : number | null;
    valFinalaFaraTvaEUR : number | null;
    valTvaEUR : number | null;
    valFinalaCuTvaEUR : number | null;
    valFinalaFaraTvaHUF : number | null;
    valTvaHUF : number | null;
    valFinalaCuTvaHUF : number | null;
    costLivrareRON : number | null;
    costLivrareEUR : number | null;
    costlivrareHUF : number | null;
    observatii : string,
    cuDebitare: string;
    sizeLengthFromSales: number | null;
    sizeWidthFromSales: number | null;
    discount_proc:number;
    nr_ord:number;
    itemChanged:boolean | false;
    val_baza_ron:number|null;
    val_baza_eur:number|null;
    val_baza_huf:number|null;
}
